server:
  port: ${PORT:8092}
  servlet:
    context-path: /bcb


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost  # Use service name from Docker Compose
    port: 5672
    username: myuser
    password: mypassword
    restart: always


  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  server:
    port: 8092