server:
  port: ${PORT:8094}
  servlet:
    context-path: /api

spring:
  rabbitmq:
    host: localhost  # Use service name from Docker Compose
    port: 5672
    username: myuser
    password: mypassword
    restart: always
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  datasource:
    url: jdbc:mysql://localhost:3306/app_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
