server:
  port: ${PORT:8090}
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  datasource:
    url: jdbc:mysql://localhost:3306/app_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: info
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/mineral/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/mineral